tool_tier: minecraft:stone
tool_category: minecraft:shears
break_speed: 4
attack_damage: 1
attack_speed: 1.5
can_sweep_attack: false
can_break_blocks_in_creative: true
max_durability: 130
durability: 130
item_damage_on_attack_entity: 2
item_damage_on_break_block: 1
enchantment_value: 10
enchantment_categories: ["digger", "breakable"]